import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/header";
import "bootstrap/dist/css/bootstrap.min.css";
import { Toaster } from "react-hot-toast";
import { UserContextProvider } from "./context/userContext";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Toaster position="top-center" />
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );
}
